name: sport-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - numpy
  - pandas
  - scipy
  - matplotlib
  - jupyter
  - ipykernel
  - pip:
      - accelerate==1.1.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - albucore==0.0.13
      - albumentations==1.4.10
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - arrow==1.3.0
      - attrs==24.3.0
      - av==13.1.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - click==8.1.7
      - cloudpickle==3.1.1
      - contourpy==1.3.1
      - cryptography==43.0.3
      - datasets==3.2.0
      - diffusers==0.31.0
      - dill==0.3.8
      - einops==0.8.0
      - fastapi==0.115.12
      - flask==3.1.0
      - fsspec==2024.9.0
      - gitpython==3.1.44
      - huggingface-hub==0.26.2
      - hydra-core==1.3.2
      - imageio==2.36.0
      - imgaug==0.4.0
      - ipywidgets==8.1.5
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jupyterlab==4.3.3
      - langchain==0.3.17
      - langchain-core==0.3.33
      - langsmith==0.3.3
      - loguru==0.7.2
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - matplotlib-inline==0.1.7
      - mistral-common==1.5.4
      - modelscope==1.24.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numba==0.60.0
      - numpy==1.26.4
      - omegaconf==2.3.0
      - openai==1.55.1
      - opencv-python==4.10.0.84
      - orjson==3.10.15
      - outlines==0.1.11
      - packaging==24.2
      - pandas==2.2.3
      - pdfminer-six==20240706
      - peft==0.13.2
      - pillow==10.4.0
      - protobuf==5.28.3
      - psutil==6.1.0
      - pydantic==2.10.2
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - sentencepiece==0.2.0
      - sqlalchemy==2.0.37
      - sympy==1.13.1
      - tiktoken==0.9.0
      - torch==2.6.0
      - torchvision==0.21.0
      - torchaudio==2.6.0
      - tqdm==4.67.1
      - transformers==4.50.2
      - typer==0.15.2
      - typing-extensions==4.12.2
      - uvicorn==0.34.0
      - wandb==0.19.8
      - websocket-client==1.8.0
      - websockets==14.1
      - xformers==0.0.29.post2 # (Uncomment if you have a compatible GPU and need xformers)
      - zstandard==0.23.0
